server:
  port: 8082
  servlet:
    context-path: /cloud-discovery
eureka:
  instance:
    hostname: localhost
    status-page-url: http://localhost:${server.port}/cloud-discovery/swagger-ui.html
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://localhost:8082/cloud-discovery/eureka/




spring:
  security:
    basic:
      enabled: true
    user:
      password: admin123
      name: admin

