server:
  port: 8060

myconfig:
  server:
    ip: localhost

eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:admin123@${myconfig.server.ip}:8082/eureka/
turbine:
  app-config: app-store,app-goods,app-datacenter
  combine-host-port: true
  cluster-name-expression: new String("default")

spring:
  application:
    name: app-hystrix