spring:
  application:
    name: app-getway
server:
  port: 8040

myconfig:
  server:
    ip: localhost

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://admin:admin123@${myconfig.server.ip}:8082/eureka/

zuul:
  host:
    connect-timeout-millis: 1000
    socket-timeout-millis: 6000
  ignoredServices: '*'
  routes:
    store:
      path: /store/**
      serviceId: app-store
    goods:
      path: /goods/**
      serviceId: app-goods
ribbon:
  ReadTimeout: 6000
  ConnectTimeout: 6000
hystrix:
    command:
        default:
            execution:
                isolation:
                    thread:
                        timeoutInMilliseconds: 6000

