server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:admin123@localhost:8082/eureka/
spring:
  profiles:
    # native：启动从本地读取配置文件，必须指定active的值，才可以使用本地文件配置模式
    active: native
    # 自定义配置文件路径
  cloud:
    config:
      server:
        native:
          searchLocations: classpath:/config
  application:
    name: cloud-config





